version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: fm
      MONGO_INITDB_ROOT_PASSWORD: fm
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: